name: Build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/LICENSE'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
      - '**/LICENSE'

env:
  BUILD_NUMBER: ${{ github.run_number }}
  PROJECT_PATH: "cs2rtv/cs2rtv.csproj"
  PROJECT_NAME: "cs2rtv"
  OUTPUT_PATH: "./cs2rtvlite"

jobs:

  publish:
    if: github.event_name == 'push'
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} -c cs2rtv -o ${{ env.OUTPUT_PATH }}
    - name: Archive build
      uses: actions/upload-artifact@v4
      with:
        name: cs2rtvlite
        path: cs2rtvlite
        retention-days: 5
